In [4]:
import sys
!{sys.executable} -m pip install pandas numpy matplotlib


   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 670.5 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/8.1 MB 670.5 kB/s eta 0:00:12
   ----- ---------------------------------- 1.0/8.1 MB 804.7 kB/s eta 0:00:09
   ------ --------------------------------- 1.3/8.1 MB 939.0 kB/s eta 0:00:08
   ------- -------------------------------- 1.6/8.1 MB 995.8 kB/s eta 0:00:07
   --------- ------------------------------ 1.8/8.1 MB 1.1 MB/s eta 0:00:06
   ----------- ---------------------------- 2.4/8.1 MB 1.2 MB/s eta 0:00:05
   ------------ --------------------------- 2.6/8.1 MB 1.2 MB/s eta 0:00:05
   --------------- ------------------------ 3.1/8.1 MB 1.3 MB/s eta 0:00:04
   ---------------- ----------

In [7]:
import sys
!{sys.executable} -m pip install seaborn

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb


In [9]:
from sklearn.datasets import make_classification

In [10]:
make_classification()

(array([[ 1.27640776, -0.98204621, -0.03088707, ...,  1.82220201,
         -0.51270675, -1.21158632],
        [ 0.79776057, -1.10455097, -0.34993693, ...,  0.90254002,
         -2.6498768 , -0.63601014],
        [ 1.38078319, -0.51071313,  1.07204858, ...,  0.46262302,
          2.61380757, -0.38272304],
        ...,
        [ 0.76499015,  0.47486392, -1.1950963 , ..., -2.9913707 ,
         -1.786212  ,  1.74699242],
        [ 0.64173517,  0.5102881 , -0.03583127, ...,  0.84038718,
         -1.19929128, -0.5456666 ],
        [-0.34910107, -0.7416277 , -1.86511727, ..., -1.02166001,
          0.33833073,  0.55915589]], shape=(100, 20)),
 array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0]))

In [11]:
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [12]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [13]:
pd.DataFrame(y)

0
0    0
1    1
2    1
3    0
4    1
..  ..
995  1
996  1
997  0
998  0
999  0

[1000 rows x 1 columns]

In [15]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.3)

In [17]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [20]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [26]:
y_pred = logistic.predict(X_test)

In [27]:
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1
 1 1 1 0]


In [28]:
X_test

array([[ 0.74030596,  0.42548993,  0.6039124 , ..., -0.709441  ,
        -0.98264957, -1.3716737 ],
       [-1.49577819,  0.38135283, -1.2763343 , ...,  0.57404193,
         1.80201193, -0.63014283],
       [-0.14407863, -0.00928856,  0.02366179, ..., -0.34287886,
         0.65257238,  1.8134077 ],
       ...,
       [-0.12931965, -2.03235376, -0.14078221, ..., -1.13106724,
         0.05635542,  0.02109275],
       [ 0.75437545, -0.46849611,  0.14582362, ..., -0.65367914,
        -2.53554104,  1.35085233],
       [ 0.77392435, -2.48832735,  0.66837144, ..., -0.98229403,
        -0.90627015,  0.45350871]], shape=(300, 10))

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [38]:
score=accuracy_score(y_test,y_pred)
print(score)


ValueError: Classification metrics can't handle a mix of binary and continuous-multioutput targets